<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NSubstitute" Version="5.1.0" />
		<PackageReference Include="Moq" Version="4.18.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Console\WordAnalytics.Cli.csproj" />
	  <ProjectReference Include="..\Counting\WordAnalytics.Counting.csproj" />
	  <ProjectReference Include="..\Ranking\WordAnalytics.Ranking.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
